### ISSUE TITLE
cant change the avatar (used .glb and .fbx)

### ISSUE THREAD

**Issue by chang998** [met4citizen/TalkingHead#12]
for a long time i was making a 3d character and after ive done it i tied to import it to talking head app but it made a loading at the top left but nothing happened the way i used to import it is to go to avatar> (file emoji) > avatar.glb or avatar.fbx (i used both formats) but nothing happened i did it many times but nothing happened can you tell me what to do ?
or if this an error help me fix it

(edit): i downloaded the 3d model that you provided as an example in this : "https://github.com/met4citizen/TalkingHead/issues/3#issuecomment-1938145043" it did the same issue im thinking if my version is broken i will reinstall it and if it worked i will try to delete this issue or close it

(another edit): still it didnt work even after replacing the main character file with the same name :(
_______________________________________________________________________________________________________________
(btw thanks for helping me to sync the chatbot script and tts both working now :) .)

**Comment by met4citizen** [comment]
Let's first check that you can open files locally. That example URL was for the same avatar that is used in the project, so you shouldn't see any change. Here is another example for you to try that looks different:

https://models.readyplayer.me/654d15b95f919c5b8ade43e2.glb?morphTargets=ARKit,Oculus+Visemes,mouthOpen,mouthSmile,eyesClosed,eyesLookUp,eyesLookDown&textureSizeLimit=1024&textureFormat=png

Download the GLB file locally and try to open it. If that doesn't work, please let me know which browser you are using, and check if there are any errors in the browser's console log.

**Comment by chang998** [comment]
Nope it doesnt

**Comment by met4citizen** [comment]
What browser are you using? Is it the latest version? Are there any errors in the browser's console log?

This doesn't require TTS proxies or API keys, so you can also try it here on GitHub:

https://met4citizen.github.io/TalkingHead/

**Comment by chang998** [comment]
well there is something weird just happened lt was late so i shutdown my pc and after two days (today) i saw your message and went to try it and intercepting the error .. the character changed somehow  ( i guess it needed to restart the service in xampp) 

BUT still my custom character isnt uploaded but yours is working (btw i upload them localy not by a url)

and also i tried my custom character in your website but it still didnt work

if you want me to give you the custom character ok
