### ISSUE TITLE
Error: 429 

### ISSUE THREAD

**Issue by UncleBob2** [met4citizen/TalkingHead#13]
thanks for creating the new demo file but I am getting error 429. using your code

<!DOCTYPE html>
<html>
<head>
  <title>Talking Head - MP3 example</title>

  <style>
    body, html { width:100%; height:100%; margin: 0; padding: 0; background-color: dimgray; color: white; }
    #avatar { display: block; position: absolute; top: 0; left: 0; right: 40%; bottom: 0; }
    #controls { display: flex; flex-direction: column; gap: 10px; position: absolute; top: 50px; left: Calc( 60% + 50px); right: 50px; bottom: 50px;  }
    #load { font-family: Arial; font-size: 20px; }
    #json { flex: 1; background-color: lightgray; font-family: Arial; font-size: 20px; }
    #play { font-family: Arial; font-size: 20px; }
    #loading { display: block; position: absolute; top: 50px; left: 50px; width: 200px; font-family: Arial; font-size: 20px; }
  </style>

  <script type="importmap">
  { "imports":
    {
      "three": "https://cdn.jsdelivr.net/npm/three@0.161.0/build/three.module.js/+esm",
      "three/examples/": "https://cdn.jsdelivr.net/npm/three@0.161.0/examples/",
      "three/addons/": "https://cdn.jsdelivr.net/npm/three@0.161.0/examples/jsm/",
      "dompurify": "https://cdn.jsdelivr.net/npm/dompurify@3.0.6/+esm",
      "marked": "https://cdn.jsdelivr.net/npm/marked@11.2.0/+esm",
      "talkinghead": "https://cdn.jsdelivr.net/gh/met4citizen/TalkingHead@1.1/modules/talkinghead.mjs"
    }
  }
  </script>

  <script type="module">
    import { TalkingHead } from "talkinghead";

    let head; // TalkingHead instance
    let audio; // Audio object

    // Make a transcription of an audio file using OpenAI's Whisper API
    async function loadAudio(file) {

      try {
        const nodeJSON = document.getElementById('json');
        nodeJSON.value = "Please wait...";

        const nodePlay = document.getElementById('play');
        nodePlay.disabled = true;

        // OpenAI Whisper request
        const form = new FormData();
        form.append("file", file);
        form.append("model", "whisper-1");
        form.append("language", "en");
        form.append("response_format", "verbose_json" );
        form.append("timestamp_granularities[]", "word" );
        form.append("timestamp_granularities[]", "segment" );

        // NOTE: Never put your API key in a client-side code unless you know
        //       that you are the only one to have access to that code!
        const response = await fetch( "https://api.openai.com/v1/audio/transcriptions" , {
          method: "POST",
          body: form,
          headers: {
            "Authorization": "Bearer " // <- Change this
          }
        });

        if ( response.ok ) {

          const json = await response.json();
          nodeJSON.value = JSON.stringify(json, null, 4);

          // Fetch audio
          if ( json.words && json.words.length ) {

            var reader = new FileReader();
            reader.readAsArrayBuffer(file);

            reader.onload = async readerEvent => {
              let arraybuffer = readerEvent.target.result;
              let audiobuffer = await head.audioCtx.decodeAudioData(arraybuffer);

              // TalkingHead audio object
              audio = {
                audio: audiobuffer,
                words: [],
                wtimes: [],
                wdurations: [],
                markers: [],
                mtimes: []
              };

              // Add words to the audio object
              json.words.forEach( x => {
                audio.words.push( x.word );
                audio.wtimes.push( 1000 * x.start - 150 );
                audio.wdurations.push( 1000 * (x.end - x.start) );
              });

              // Callback function to make the avatar look at the camera
              const startSegment = async () => {
                head.lookAtCamera(500);
                head.speakWithHands();
              };

              // Add timed callback markers to the audio object
              json.segments.forEach( x => {
                if ( x.start > 2 && x.text.length > 10 ) {
                  audio.markers.push( startSegment );
                  audio.mtimes.push( 1000 * x.start - 1000 );
                }
              });

              // Enable play button
              nodePlay.disabled = false;
            }
          }

        } else {
          nodeJSON.value = 'Error: ' + response.status + ' ' + response.statusText;
          console.log(response);
        }

      } catch (error) {
        console.log(error);
      }
    }

    document.addEventListener('DOMContentLoaded', async function(e) {

      // Instantiate the class
      // NOTE: Text-to-speech not initialized
      const nodeAvatar = document.getElementById('avatar');
      head = new TalkingHead( nodeAvatar, {
        ttsEndpoint: "https://eu-texttospeech.googleapis.com/v1beta1/text:synthesize",
        cameraView: "head"
      });

      // Load and show the avatar
      const nodeLoading = document.getElementById('loading');
      try {
        await head.showAvatar( {
          url: 'https://models.readyplayer.me/64bfa15f0e72c63d7c3934a6.glb?morphTargets=ARKit,Oculus+Visemes,mouthOpen,mouthSmile,eyesClosed,eyesLookUp,eyesLookDown&textureSizeLimit=1024&textureFormat=png',
          body: 'F',
          avatarMood: 'neutral',
          lipsyncLang: 'en'
        }, (ev) => {
          if ( ev.lengthComputable ) {
            let val = Math.min(100,Math.round(ev.loaded/ev.total * 100 ));
            nodeLoading.textContent = "Loading " + val + "%";
          }
        });
        nodeLoading.style.display = 'none';
      } catch (error) {
        console.log(error);
        nodeLoading.textContent = error.toString();
      }

      // File changed
      const nodeLoad = document.getElementById('load');
      nodeLoad.addEventListener('change', function(ev) {
        let file = ev.target.files[0];
        loadAudio(file);
      });

      // Play button clicked
      const nodePlay = document.getElementById('play');
      nodePlay.addEventListener('click', function() {
        if ( audio ) {
          head.speakAudio( audio );
        }
      });

    });

  </script>
</head>

<body>
  <div id="avatar"></div>
  <div id="controls">
    <input id="load" type="file" accept=".m4a,.mp3,.webm,.mp4,.mpga,.wav,.mpeg">
    <textarea id="json" readonly></textarea>
    <input id="play" type="button" value="Play" disabled="disable">
  </div>
  <div id="loading"></div>
</body>

</html>

**Comment by UncleBob2** [comment]
is there another way to display some of the log? What about fetchwithretry?

        // Add this function inside your <script type="module"> tag
    async function fetchWithRetry(url, options, maxAttempts = 3, attempt = 1) {
    const response = await fetch(url, options);
    if (!response.ok) {
        // Check if the response status is 429 (Too Many Requests) and we have more attempts left
        if (response.status === 429 && attempt < maxAttempts) {
        // Calculate wait time using exponential backoff. For simplicity, 2 seconds base wait time.
        const waitTime = Math.pow(2, attempt) * 2000; // Exponential backoff formula
        console.log(`Rate limit hit, retrying in ${waitTime / 1000} second(s)...`);
        await new Promise(resolve => setTimeout(resolve, waitTime));
        return fetchWithRetry(url, options, maxAttempts, attempt + 1); // Retry the fetch
        } else {
        // Throw an error if not 429 or no attempts left
        throw new Error(`Fetch failed with status: ${response.status} after ${attempt} attempts`);
        }
    }
    return response; // Return the successful response
    }

**Comment by met4citizen** [comment]
Thank you for the suggestion. I appreciate it.

I was wondering if you are actually getting something other than the rate limit error? At least for me, the Whisper-1 rate limit is 100 RPM, and it is unlikely that you could generate that much traffic using the example app. Unless, of course, you are using your API key in other Whisper apps at the same time.

According to OpenAI documentation, other 429 errors include "You exceeded your current quota" and "The engine is currently overloaded". You can check the exact error from the browser's network log.

If this were a production app, I would definitely be in favor of some kind of retry logic, and your approach seems a potential solution. And it works for the "overloaded" error, too.

On the other hand, I would like to keep the example code as simple as possible. The main purpose of the example code is to present developers the general idea for how to add the TalkingHead class into their own apps, and I'm counting on them to already have some kind of logging and error handling in place.

**Comment by UncleBob2** [comment]
I am using this 10-second wave file from your youtube video. I just wanted to replicate your example https://github.com/UncleBob2/TalkingHead/tree/main/examples

**Comment by met4citizen** [comment]
I tried your WAV file multiple times on the latest versions of Chrome, Firefox, and Safari, and I didn't encounter any issues. Everything worked fine.

If you're still experiencing errors, it might be linked to your OpenAI API key or subscription. OpenAI error messages usually provide more details, so you can open your browser's network log, retry, and review the response. If it indicates a rate limit problem (which seems unlikely), you can check the `X-ratelimit` response headers for more information.

**Comment by UncleBob2** [comment]
Thank you for your prompt response. Greatly appreciated.
