### ISSUE TITLE
More realism via Controlnet Stable Diffusion?

### ISSUE THREAD

**Issue by JPhilipp** [met4citizen/TalkingHead#17]
Again, fantastic project! I was wondering if it was possible to locally hook this up to something like controlnet stable diffusion to create an output layer that would turn the ReadyPlayerMe avatar to look like a realistic, photographic face.

I'm sure this is outside the scope of this great library but I just wanted to mention it. Imagine a real-looking avatar thanks to AI!

**Comment by met4citizen** [comment]
Thanks. Yes, the TalkingHead is meant to be a real-time JavaScript class, so this is, as you said, a bit outside of the scope. However, technologies are developing fast and there will be (and already are) a lot of interesting things you can do by mixing them. For example, a couple of weeks ago I had a chance to test a text-to-3D animation tool, and I know there are also companies developing AI tools for generating realistic 3D characters.
