### ISSUE TITLE
Mood ignored?

### ISSUE THREAD

**Issue by JPhilipp** [met4citizen/TalkingHead#19]
Hi! When trying the [mp3.html](/met4citizen/TalkingHead/blob/main/examples/mp3.html) example and changing the avatarMood from 'neutral' to e.g. 'happy' or 'angry', it will still remain neutral.

(This even happens if I amend the code to not cause a 'user gesture required' warning in Chrome.)

Help please?

**Comment by met4citizen** [comment]
Yes, you are right. Thank you. I will fix it. In the meantime, you can change the mood by calling, for example, `head.setMood("angry")`.

**Comment by JPhilipp** [comment]
Works great, thanks!
