### ISSUE TITLE
Bad mouth effect during speaking

### ISSUE THREAD

**Issue by branaway** [met4citizen/TalkingHead#35]
Currently the mouth templates in the mood configurations interferes with the visemes and render bad looking lip shapes. Should it ignore the mouth template in the moods while the avatar is speaking?

**Comment by met4citizen** [comment]
You are right. Each mood has its own baseline expression, and the mouth doesn't always look natural while speaking. If I completely ignore the mouth's baseline while speaking, however, it will make the avatar look a bit too happy even when angry/sad. Perhaps a good compromise is to restrict the mouth's baseline values to one-third (or something) while speaking. I will look into this. Thank you.

**Comment by branaway** [comment]
I saw the changes. Thanks! That helps a lot.
