### ISSUE TITLE
Callback for speech end

### ISSUE THREAD

**Issue by anmol1905** [met4citizen/TalkingHead#37]
Hello,

Amazing work! 
Is there any way to know that the speech ended after calling the head.speakAudio() function?

**Comment by met4citizen** [comment]
Thanks! Yes, once you have called the `head.speakAudio`, you can add a new marker to the speech queue by calling `head.speakMarker(onmarker)`. The callback function `onmarker` is called when the class reaches the marker, which will be right after the audio has ended.
