### ISSUE TITLE
All eye movement directives not affecting the eyeballs

### ISSUE THREAD

**Issue by branaway** [met4citizen/TalkingHead#39]
This may be related to specific ready player me model used, but I have found that none of the eye related blendshapes has impact on the eye ball position. Looking up/down/left/right etc has no effect on eyeballs.  I suspect the eyes can only be moved by changing the quaternions of eye "bones".

**Comment by met4citizen** [comment]
Ready Player Me avatars have two skinned meshes named `EyeLeft`and `EyeRight`. The eye related blend shape values affect those skinned meshes. The eye bones named `LeftEye` and `RightEye` are not moved (and don't have to be moved).

**Comment by branaway** [comment]
Ha I got it! Thanks for the information.
