### ISSUE TITLE
ikSolve and disappeared bones

### ISSUE THREAD

**Issue by branaway** [met4citizen/TalkingHead#40]
Double clicks on the avatar body would cause the hand movements towards the points. But the hands and fingers would disappear when the camera is too close to the subject.  see the attachments. 
![Screen Shot 2024-05-13 at 16 27 55](https://github.com/met4citizen/TalkingHead/assets/179513/418758e6-eeb9-4292-9ead-b7ef3f23a4c6)
![Screen Shot 2024-05-13 at 16 27 16](https://github.com/met4citizen/TalkingHead/assets/179513/acc10887-1f4a-4fbe-956a-880ef000d95b)

**Comment by met4citizen** [comment]
Thanks. The issue is not directly related to ikSolve. For some reason, three.js decides that the object is outside the view frustum and it is culled from the rendering process. The only workaround I can think of is to set the `frustumCulled` property to `false`. I'll make the change.

**Comment by branaway** [comment]
Thanks for the update.
