### ISSUE TITLE
Increase volume for openAI's tts and whisper integration

### ISSUE THREAD

**Issue by anmol1905** [met4citizen/TalkingHead#43]
Right now when I integrate open AI's TTS and Whisper for the visemes and call the startSpeaking function. The volume seems to be low. is there any configuration required in TalkingHead module or do I need to tweak it with other methods?

**Comment by met4citizen** [comment]
The TalkingHead class uses a gain node, and you can increase the volume with the `setMixerGain` method. The first parameter is for speech, and the second is for background audio (if any).

```javascript
head.setMixerGain(10,0);
```

**Comment by anmol1905** [comment]
Thank you!
