### ISSUE TITLE
divides tts sentences

### ISSUE THREAD

**Issue by Nick-8520** [met4citizen/TalkingHead#47]
Hello there. Ive made the same issue before in a different account you may not remember it but you told me to do this:
const dividersSentence = /[\p{Extended_Pictographic}]/ug;
it was working fine but for some reason one day it divided the sentences again so i installed the latest version and made the same thing that i did in the old one but still didnt work. BTW here is the python server logs for knowing what is happening:
___________________________________________________________________________________________________________________________________
 * Serving Flask app 'apimain'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:6699
Press CTRL+C to quit
127.0.0.1 - - [21/Jun/2024 22:52:26] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2024 22:52:26] "OPTIONS /moderation_ai HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2024 22:52:26] "POST /moderation_ai HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2024 22:52:26] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2024 22:52:26] "OPTIONS /chatbot HTTP/1.1" 200 -
Received request data: {'model': 'gpt-3.5-turbo', 'messages': [{'role': 'user', 'content': 'nick: hi there this is just a test.'}], 'temperature': 1, 'presence_penalty': 0, 'frequency_penalty': 0, 'max_tokens': 1000, 'stream': True}
Last message: {'role': 'user', 'content': 'nick: hi there this is just a test.'}
Content of last message: nick: hi there this is just a test. <-- my message
typing message
sent
Finding response...
Captcha button not found, proceeding without interaction.
Matches found:
2b: Hey there, no problem, just testing things out. Always good to make sure everything is working properly. *winks* <-- the response
Only one match found: 2b: Hey there, no problem, just testing things out. Always good to make sure everything is working properly. *winks* <-- it returns it to talking head 
127.0.0.1 - - [21/Jun/2024 22:52:39] "POST /chatbot HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2024 22:52:39] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2024 22:52:39] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2024 22:52:39] "OPTIONS /gtts HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2024 22:52:39] "OPTIONS /moderation_ai HTTP/1.1" 200 -
twob Hey there, no problem, just testing things out. <-- for some reason it divides it
127.0.0.1 - - [21/Jun/2024 22:52:39] "POST /moderation_ai HTTP/1.1" 200 -
#generates audio
127.0.0.1 - - [21/Jun/2024 22:53:22] "POST /gtts HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2024 22:53:25] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2024 22:53:25] "OPTIONS /gtts HTTP/1.1" 200 -
Always good to make sure everything is working properly. <-- divided sentence
#generates audio
Done.
127.0.0.1 - - [21/Jun/2024 22:54:16] "POST /gtts HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2024 22:54:20] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2024 22:54:20] "OPTIONS /gtts HTTP/1.1" 200 -
winks <-- last divided sentence
#generates audio
127.0.0.1 - - [21/Jun/2024 22:55:01] "POST /gtts HTTP/1.1" 200 -
____________________________________________________________________________________________________________________________
so as you can see it divides the text and then sends it back and i dont want that bec it takes a long time (20s) generating the audio bec it uses a hugging face coqui tts through api so it will reaaaallly take a long time just to say something but when its not divided it will normally read it well. is there a way to divide it? (i tried const dividersSentence = /[\p{Extended_Pictographic}]/ug; but it still didnt work) Thanks!

**Comment by met4citizen** [comment]
If I remember correctly, you are using the `speakText` method. There haven't been any recent changes to that method, so if you don't want the method to divide the text into sentences, changing the line `const dividersSentence = /[!\.\?\n\p{Extended_Pictographic}]/ug;` to `const dividersSentence = /[\p{Extended_Pictographic}]/ug;` should be enough.

Browsers typically cache modules, so make sure that you are using the updated module. Assuming you are using Chrome, navigate to the page, open Developer Tools, right-click on the Reload button, and choose "Empty cache and hard reload".

**Comment by Nick-8520** [comment]
thanks i think this worked i think but ive did this but it still didnt work even i deleted the whole browser data using ccleaner but for some reason it worked this time THANKS

**Comment by Nick-8520** [comment]
im sorry for doing this too much but there is a problem look:
________________________________________________________
2b: Aw, Thanks, Nick. I owe you one now. *waves*
Only one match found: 2b: Aw, Thanks , Nick. I owe you one now. *waves*
127.0.0.1 - - [28/Jun/2024 20:45:54] "POST /chatbot HTTP/1.1" 200 -
127.0.0.1 - - [28/Jun/2024 20:45:54] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [28/Jun/2024 20:45:54] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [28/Jun/2024 20:45:54] "OPTIONS /gtts HTTP/1.1" 200 -
127.0.0.1 - - [28/Jun/2024 20:45:54] "OPTIONS /moderation_ai HTTP/1.1" 200 -
127.0.0.1 - - [28/Jun/2024 20:45:54] "POST /moderation_ai HTTP/1.1" 200 -
twob Aw, Thanks, Nick. I owe you one now.
#generates voice
127.0.0.1 - - [28/Jun/2024 20:47:07] "POST /gtts HTTP/1.1" 200 -
127.0.0.1 - - [28/Jun/2024 20:47:12] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [28/Jun/2024 20:47:12] "OPTIONS /gtts HTTP/1.1" 200 -
waves
_____________________________________________________________________________________________________

now for some other reason it separates sentences between two *
can you help?

**Comment by met4citizen** [comment]
I couldn't reproduce your issue. I tested the phrase in my test environment by calling `head.speakText("Aw, Thanks , Nick. I owe you one now. waves")`. Without the code change, the class made three requests as expected, but with the change, it sent everything in one message without splitting.

I don't know your setup, but are you using any code from the test app `index.html`? If so, note that it also splits sentences to ensure the streaming response is sent as soon as possible but without splitting mid-sentence. For example, in `openaiSendMessage` method, there is a section with the following line:

```javascript
let idx = Math.max(tts.lastIndexOf('.'), tts.lastIndexOf('!'), tts.lastIndexOf('?'), tts.lastIndexOf('\n'));
```

Now, if you have that in your code that could explain your issue. To prevent the split, just change the above line to `let idx = -1`.

**Comment by Nick-8520** [comment]
well look it sometimes divides it and sometimes not but i think you didnt understand me well that last message it doesnt divide the (.-!-?-/n) but the words between two * like in this log:

_____________
2b: Aw, Thanks, Nick. I owe you one now. (*waves*) <------ between two **
Only one match found: 2b: Aw, Thanks , Nick. I owe you one now. *waves* <------ see
127.0.0.1 - - [28/Jun/2024 20:45:54] "POST /chatbot HTTP/1.1" 200 -
127.0.0.1 - - [28/Jun/2024 20:45:54] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [28/Jun/2024 20:45:54] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [28/Jun/2024 20:45:54] "OPTIONS /gtts HTTP/1.1" 200 -
127.0.0.1 - - [28/Jun/2024 20:45:54] "OPTIONS /moderation_ai HTTP/1.1" 200 -
127.0.0.1 - - [28/Jun/2024 20:45:54] "POST /moderation_ai HTTP/1.1" 200 -
twob Aw, Thanks, Nick. I owe you one now. <-------- removed here 
#generates voice
127.0.0.1 - - [28/Jun/2024 20:47:07] "POST /gtts HTTP/1.1" 200 -
127.0.0.1 - - [28/Jun/2024 20:47:12] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [28/Jun/2024 20:47:12] "OPTIONS /gtts HTTP/1.1" 200 -
waves <-------- alone here
#generates voice
______________________________________________________________________
its actually written like this:`*waves*` but github doesnt show the two *
anyway it divides it for some reason

btw: it sometimes do this and sometimes not idk why

**Comment by met4citizen** [comment]
I tried it with \*waves\* now, but still couldn't reproduce the issue.

The regex `/[\p{Extended_Pictographic}]/ug` doesn't match a normal * character, but it does match emojis, so are you sure that \*waves\* isn't actually an emoji being converted to text when printed to the log?

**Comment by Nick-8520** [comment]
well can i remove the \p and now it wont cut anything

But if It still cut it what do i do to make it not cut anything?

**Comment by met4citizen** [comment]
If you don't want to split on anything, change the line to `const dividersSentence = /[]/ug;`.
