### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Nick-8520** [met4citizen/TalkingHead#50]
im sorry but this is not an issue but i want a private contact info i just want help

if you dont want to share any private contact info here there is mine (telegram)

![telegram](https://github.com/user-attachments/assets/8370744e-2a49-4a53-841a-76bf9a4c4592)

im sorry but if you dont have telegram can you make one and if you delete it later i dont care but i reaaly need you bec you know js (ive contacted you before many times)

send me a message and when we talk we talk at secret chat THANKS !!!!

after you add me if i didnt respond for a while comment your name (not your username for privacy) and ill search for you bec i have too many chats

**Comment by met4citizen** [comment]
I'm sorry, but I don't provide this kind of personal support. I have allocated some time to develop the TalkingHead class and to answer related issues, but otherwise, I'm fully engaged in my other projects. Thank you for your understanding.

**Comment by Nick-8520** [comment]
Oh i can understand but its just something real quick but its important. its about javascript too can you just contact me and ill tell you about it if you decline i have no problem.
