### ISSUE TITLE
Audio not playing in Safari

### ISSUE THREAD

**Issue by AkshatRastogi-1nC0re** [met4citizen/TalkingHead#56]
I created a website using the minimal template you provided. The website works perfectly when used on Google chrome. But for some reason the avatar doesn't speak on Safari or on iPhone in any browser. I debugged the code the tts api key is retrieved from the proxy properly, the text is also going into head.SpeakText function. Console logs no errors. I checked if its apple that has some kind of restrictions, turns out they do have an autoplay limitation, but I specifically went to my safari settings and clicked on the option where all sites are now allowed to autoplay. But still I am facing that issue. Is there anything else that I can try ?

**Comment by AkshatRastogi-1nC0re** [comment]
I am so embarrassed but I had my iphone's physical switch for silent on this whole time, spent like 5 hours trying out stuff and getting mad at Apple.

**Comment by AkshatRastogi-1nC0re** [comment]
Btw, I have created my own portfolio using this, you can check it out at https://akshatrastogi.in 
If you do like it, I'd love to get my website featured in your readme section.

**Comment by met4citizen** [comment]
No problem, these kinds of things happen to me all the time... 😀

I tried your app, and I really like the idea of having a personal portfolio where you can ask questions and explore topics that interest you the most. I'm happy to include it in my use case examples sometime later this week.

**Comment by met4citizen** [comment]
I just added your app to the use case examples. - I'll close this issue, but feel free to reply if you’d like to adjust the wording or suggest any other changes. Thank you for using the TalkingHead class!
