### ISSUE TITLE
hi, is there any way to make the lips speak like a human? right now I only see them open and close, not make human-like mouth shapes.

### ISSUE THREAD

**Issue by D-Mad** [met4citizen/TalkingHead#57]

**Comment by met4citizen** [comment]
Ready Player Me avatars have a limited set of viseme blend shapes (14), so there's not much room for improvement using our approach. You might want to look into some AI-based talking head projects. While they have their own issues and typically don't run in a browser, the lip movements can appear very human-like.

**Comment by namnm** [comment]
@D-Mad Here are some refs I found open source repos on GitHub:
https://github.com/Rudrabha/Wav2Lip
https://github.com/KwaiVGI/LivePortrait
https://github.com/OpenTalker/video-retalking
https://github.com/OpenTalker/SadTalker
