### ISSUE TITLE
 Impulse responses library 

### ISSUE THREAD

**Issue by audreytimbani** [met4citizen/TalkingHead#60]
@met4citizen Do you have any idea where I can find more impulse responses ?

**Comment by met4citizen** [comment]
In this project, I used impulse response data from [OpenAir](https://www.openair.hosted.york.ac.uk/?page_id=36). I haven't extensively explored other sources, but the following repository provides a list of publicly available room impulse response datasets:

https://github.com/RoyJames/room-impulse-responses

**Comment by audreytimbani** [comment]
Thanks you
