### ISSUE TITLE
Get the text of the current audio chunk played in real time 

### ISSUE THREAD

**Issue by audreytimbani** [met4citizen/TalkingHead#61]
Let's suppose that the avatar has to say: ‘Hello World . I'm John’, is there a way of knowing which word the avatar is on so that it can be displayed on the screen in real time?

**Comment by met4citizen** [comment]
For the `speakText` and `speakAudio` methods, you can provide your callback function as the third parameter to get the word currently being spoken. Here’s a simple example:

```javascript
head.speakText("Hello World. I'm John.", {}, (word) => {
  console.log(word);
});
```

**Comment by audreytimbani** [comment]
Thanks
