### ISSUE TITLE
Difference betweem the quality on reader player me hub and the talkinghead output

### ISSUE THREAD

**Issue by audreytimbani** [met4citizen/TalkingHead#62]
Hello @met4citizen  , i remark the difference of quality between the model created on reader player me hub itself (preview)  and the one talking head is fetching . 
**From rpm hub :** 

![image](https://github.com/user-attachments/assets/4364d6ec-a30c-4a83-8afc-c17eff5b2506)
![image](https://github.com/user-attachments/assets/d16cf289-fdbf-4ae8-a0b0-3f33fcdeacc1)

**With talking head example code :**

![image](https://github.com/user-attachments/assets/b1fe55a3-468f-49ab-80dc-9d712934fd7c)

Please How to fix that ? 

This is the model id : 66f55316e9a27f067c0d0e04

**Comment by met4citizen** [comment]
I don't believe there are differences in model quality. The Ready Player Me Hub just uses different lighting and other settings.

Here is a screenshot of your model from the TalkingHead test app, with a dark background and some added lighting.

![manwithhat](https://github.com/user-attachments/assets/33b2ac02-3602-4c32-809b-fded306439be)

If you'd like to use TalkingHead's built-in lights (like I did here) you can modify the lighting using the following options: `lightAmbientColor`, `lightAmbientIntensity`, `lightDirectColor`, `lightDirectIntensity`, `lightDirectPhi`, `lightDirectTheta`, `lightSpotColor`, `lightSpotIntensity`, `lightSpotPhi`, `lightSpotTheta`, and `lightSpotDispersion`. You can find more details about these options in the project's Readme.

**Comment by audreytimbani** [comment]
Got it mika , thanks
