### ISSUE TITLE
Can't download examples?

### ISSUE THREAD

**Issue by maxbatt22** [met4citizen/TalkingHead#63]
Hello!

This looks so cool. However when I try to download to check out the examples, only the "module" folder downloads. Any way to download everything?

**Comment by met4citizen** [comment]
Hi. There are currently two single-file examples available. To download them, simply open [minimal.html](https://github.com/met4citizen/TalkingHead/blob/main/examples/minimal.html) and/or [mp3.html](https://github.com/met4citizen/TalkingHead/blob/main/examples/mp3.html) and choose "download".

If you want to download all the latest files in the repo, you can use Git and perform a shallow clone, for example:

```bash
git clone --depth 1 https://github.com/met4citizen/TalkingHead.git && rm -r TalkingHead/.git
```
