### ISSUE TITLE
Google's Journey TTS model not compatible.

### ISSUE THREAD

**Issue by Anarbb** [met4citizen/TalkingHead#69]
The Google Journey models do not support SSML, pitch and rate, I got around this by just removing the SSML and replacing it by the text and removing the pitch and rate options.

**Comment by met4citizen** [comment]
As far as I know, using SSML and <mark> tags is the only way to get word-level timestamps with Google TTS. Only Standard, Neural2, and Casual voice types support both. At least for now, the new Journey voices do not support either.

You can, of course, remove the SSML and <mark> tags from the TalkingHead code, but this means you lose word-audio alignment information, which significantly decreases lip-sync accuracy.

Note also that the Journey voices are currently in the "Preview" stage, so hopefully Google will find a way to enable word timestamps for them before they become generally available (GA).

**Comment by met4citizen** [comment]
Added a list of currently supported Google voice types to the README's `ttsVoice` option description.
