### ISSUE TITLE
how to add my custom python chatbot script to it

### ISSUE THREAD

**Issue by chang998** [met4citizen/TalkingHead#7]
i just dont know in javascript well
i made an chatbot.py file and i wanted to connect it to the talking head ui so i used chatgpt and tried to connect it with a flask server 

this is a simple ai with the flask server 

`from flask import Flask, request, jsonify
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

chatbot = ChatBot("Ron Obvious")
conversation = [
    "Hello",
    "Hi there!",
    "How are you doing?",
    "I'm doing great.",
    "That is good to hear",
    "Thank you.",
    "You're welcome."
]
trainer = ListTrainer(chatbot)
trainer.train(conversation)

@app.route('/get_jwt')
def get_jwt():

    jwt = 'your_jwt_here'
    return jsonify({'jwt': jwt})

@app.route('/chatbot', methods=['GET'])
def chatbot_response():

    message = request.args.get('ask', '')

    res = str(chatbot.get_response(message))

    return jsonify({'res': res})

if __name__ == '__main__':
    app.run(host='127.0.0.1', port=6699)
`
and then edited those const openaiChatCompletionsProxy = "http://127.0.0.1:6699/chatbot?ask=test";
const openaiModerationsProxy = "http://127.0.0.1:6699/chatbot?ask=test";

and did this // Fetch the response from the OpenAI API
       const res = await fetch('http://127.0.0.1:6699/chatbot?ask=test');
       const data = await res.json();
      if ( res.ok ) {
after running i get this from the server logs 127.0.0.1 - - [26/Feb/2024 01:53:58] "GET /chatbot?ask=test HTTP/1.1" 200 -
127.0.0.1 - - [26/Feb/2024 01:54:10] "GET /chatbot?ask=test HTTP/1.1" 200 -
127.0.0.1 - - [26/Feb/2024 01:54:10] "OPTIONS /chatbot?ask=test HTTP/1.1" 200 -
127.0.0.1 - - [26/Feb/2024 01:54:10] "POST /chatbot?ask=test HTTP/1.1" 405 -
127.0.0.1 - - [26/Feb/2024 01:54:11] "GET /chatbot?ask=test HTTP/1.1" 200 

and this from the ui 
TypeError: Failed to execute 'getReader' on 'ReadableStream': ReadableStreamDefaultReader constructor can only accept readable streams that are not yet locked to a reader
![Screenshot 2024-02-26 015857](https://github.com/met4citizen/TalkingHead/assets/128249651/f49ae650-5dbb-4668-ab7f-6674205f3fb0)

im stuck on this error
been working on this for days cant find a solution pls help
dont wanna leave this project

**Comment by met4citizen** [comment]
My Python skills are very limited - and I have never used Flask or ChatterBot - but if I understood your code correctly, you are using TalkingHead's `index.html` and trying to replace OpenAI's GPT server/proxy with ChatterBot.

The error you are encountering is because the app uses OpenAI's streaming API and expects to receive a streamed response from the GPT. The response you provide in your code is neither a valid GPT response nor a stream. If you want to pursue this approach, you should check the response format from OpenAI's site and find out how to make a streamed response in Python/Flask.

I should also note that the `index.html` file was created just for testing the TalkingHead class, and you don't really need it. If you already have a working Python/Flask ChatterBot client, I would recommend starting with the minimal example in `./examples/minimal.html`, integrating the two, and then replacing the part where ChatterBot's response is added to the screen with a call to TalkingHead's `speakText` method.

Hope this helps.

**Comment by chang998** [comment]
im sorry for bothering but im not good with javascript so when i tried to try in minimal.html but i couldnt so i tried chatgpt and i got this results : 

firstly : this python code explained by chatgpt clearly 
Sure, let's break down the code and explain each part:

```python
from flask import Flask, request, jsonify
from flask_cors import CORS
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
```

Here, we import the necessary modules:
- `Flask`: This is the main class we use to create the Flask web application.
- `request`: It helps us access the data that the client sends to the server.
- `jsonify`: This function converts Python dictionaries into JSON format, which can be sent as responses to client requests.
- `Flask-CORS`: This extension allows Cross-Origin Resource Sharing (CORS) in our Flask application.
- `ChatBot` and `ListTrainer`: These are classes from the ChatterBot library, which we use to create and train our chatbot.

```python
app = Flask(__name__)
CORS(app)
```

We create an instance of the Flask application and enable CORS to allow cross-origin requests.

```python
chatbot = ChatBot("Miyu")
trainer = ListTrainer(chatbot)
```

We create an instance of the `ChatBot` class named "Miyu" and a `ListTrainer` instance to train the chatbot.

```python
conversation = [
    "Hello",
    "Hi there!",
    "How are you doing?",
    "I'm doing great.",
    "That is good to hear",
    "Thank you.",
    "You're welcome."
]
trainer.train(conversation)
```

We define a simple conversation and use the `trainer.train()` method to train the chatbot with this conversation.

```python
@app.route('/chatbot', methods=['GET', 'POST'])
def chatbot_response():
    if request.method == 'GET':
        # Handle GET requests
        message = request.args.get('ask', '')
        response = chatbot.get_response(message)
        res = [
            {"role": "assistant", "content": str(response)}
        ]
        return jsonify(res)
```

We define a route `/chatbot` and specify that it can handle both GET and POST requests. When a GET request is made, the function `chatbot_response()` is invoked. It retrieves the user's message from the query parameter 'ask', gets the response from the chatbot, constructs a JSON response, and returns it.

```python
    elif request.method == 'POST':
        # Handle POST requests
        request_data = request.json
        messages = request_data.get('messages', [])
        res = []
        for message in messages:
            role = message.get('role', '')
            content = message.get('content', '')
            if role == "user":
                res.append({"role": "user", "content": content})
                response = chatbot.get_response(content)
                res.append({"role": "assistant", "content": str(response)})
        return jsonify(res)
```

When a POST request is made, the function processes the JSON payload containing a list of messages. For each message, it checks if the role is 'user'. If it is, it adds the user's message to the response list, retrieves the chatbot's response, and adds it to the response list as well.

```python
if __name__ == '__main__':
    app.run(host='127.0.0.1', port=6699)
```

Finally, we start the Flask application on localhost (`127.0.0.1`) and port `6699` if the script is executed directly.
__________________________________________________________________________________________
and this is the POST test : C:\Users\name>curl -X POST -H "Content-Type: application/json" -d "{\"messages\": [{\"role\": \"user\", \"content\": \"hi\"}]}" http://127.0.0.1:6699/chatbot
[{"content":"hi","role":"user"},{"content":"How are you doing?","role":"assistant"}]
__________________________________________________
and this is the talking head application 
![image](https://github.com/met4citizen/TalkingHead/assets/128249651/71350272-03d0-43e4-926d-7a3712cf7df2)
___________________________________________________________________________________________________________________
logs : 
 * Running on http://127.0.0.1:6699
No value for search_text was available on the provided input
127.0.0.1 - - [02/Mar/2024 00:58:04] "GET /chatbot HTTP/1.1" 200 -
No value for search_text was available on the provided input
127.0.0.1 - - [02/Mar/2024 00:58:14] "GET /chatbot HTTP/1.1" 200 -
127.0.0.1 - - [02/Mar/2024 00:58:14] "OPTIONS /chatbot HTTP/1.1" 200 -
127.0.0.1 - - [02/Mar/2024 00:58:14] "POST /chatbot HTTP/1.1" 200 -
No value for search_text was available on the provided input
127.0.0.1 - - [02/Mar/2024 00:58:17] "GET /chatbot HTTP/1.1" 200 -
127.0.0.1 - - [02/Mar/2024 00:58:17] "POST /chatbot HTTP/1.1" 200 -
___________________________________________________________________________________________________________________
secondly : 
this is the other python script also explained by chatgpt : 

Let's break down the code and explain each part:

```python
from flask import Flask, request, jsonify
from flask_cors import CORS
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
import jwt
import secrets
```

Here, we import the necessary modules:
- `Flask`: This is the main class we use to create the Flask web application.
- `request`: It helps us access the data that the client sends to the server.
- `jsonify`: This function converts Python dictionaries into JSON format, which can be sent as responses to client requests.
- `Flask-CORS`: This extension allows Cross-Origin Resource Sharing (CORS) in our Flask application.
- `ChatBot` and `ListTrainer`: These are classes from the ChatterBot library, which we use to create and train our chatbot.
- `jwt`: This module allows us to encode and decode JSON Web Tokens (JWT).
- `secrets`: This module helps us generate secure random tokens.

```python
app = Flask(__name__)
CORS(app)
```

We create an instance of the Flask application and enable CORS to allow cross-origin requests.

```python
# Generate a secure random secret key
secret_key = secrets.token_hex(16)

# Set the secret key for encoding and decoding JWT tokens
app.config['SECRET_KEY'] = secret_key
```

We generate a secure random secret key using the `secrets` module and set it as the secret key for encoding and decoding JWT tokens in the Flask application.

```python
chatbot = ChatBot("Miyu")
trainer = ListTrainer(chatbot)
```

We create an instance of the `ChatBot` class named "Miyu" and a `ListTrainer` instance to train the chatbot.

```python
conversation = [
    "Hello",
    "Hi there!",
    "How are you doing?",
    "I'm doing great.",
    "That is good to hear",
    "Thank you.",
    "You're welcome."
]
trainer.train(conversation)
```

We define a simple conversation and use the `trainer.train()` method to train the chatbot with this conversation.

```python
@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET' or request.method == 'POST':
        # Dummy authentication - we generate a JWT token with a payload
        token = jwt.encode({'user': 'username'}, app.config['SECRET_KEY'])
        return jsonify({'token': token})
```

We define a route `/login` and specify that it can handle both GET and POST requests. We generate a JWT token with a payload containing the username 'username' and return it as a JSON response.

```python
@app.route('/chatbot', methods=['GET', 'POST'])
def chatbot_response():
    if request.method == 'GET':
        # Handle GET requests
        message = request.args.get('ask', '')

        # Get response from ChatterBot
        response = chatbot.get_response(message)

        # Construct JSON response
        res = {
            "choices": [
                {
                    "role": "assistant",
                    "res": {
                        "content": str(response),
                        "created": "Timestamp"
                    },
                    "index": 0,
                    "finish_reason": "string"
                }
            ]
        }

        return jsonify(res)

    elif request.method == 'POST':
        # Handle POST requests
        request_data = request.json
        messages = request_data.get('messages', [])

        # Initialize response
        res = {
            "results": []
        }

        # Process each message and generate response
        for message in messages:
            # Get content of the message
            content = message.get('content', '')

            # Get response from ChatterBot
            response = chatbot.get_response(content)

            # Construct response message
            response_message = {
                "role": "assistant",
                "content": str(response),
                "index": message.get("index", 0)
            }

            # Append response message to results
            res['results'].append(response_message)

        return jsonify(res)
```

We define a route `/chatbot` and specify that it can handle both GET and POST requests. When a GET request is made, the function retrieves the user's message from the query parameter 'ask', gets the response from the chatbot, constructs a JSON response, and returns it. When a POST request is made, the function processes the JSON payload containing a list of messages. For each message, it retrieves the chatbot's response, constructs a response message, and adds it to the response list. Finally, it returns the response as JSON.

```python
if __name__ == '__main__':
    app.run(host='127.0.0.1', port=6699)
```

Finally, we start the Flask application on localhost (`127.0.0.1`) and port `6699` if the script is executed directly.
_______________________________________________________________
post test : 
C:\Users\name>curl -X POST -H "Content-Type: application/json" -d "{\"messages\": [{\"role\": \"user\", \"content\": \"hi\"}]}" http://127.0.0.1:6699/chatbot
{"results":[{"content":"Hello","index":0,"role":"assistant"}]}
_______________________________________________________________________________________
talking head 
![Screenshot 2024-03-02 002351](https://github.com/met4citizen/TalkingHead/assets/128249651/01c1a6c9-a741-4984-88d5-e4a86ece0ec8)
_______________________________________________________________________________________
logs : 
 * Running on http://127.0.0.1:6699
127.0.0.1 - - [02/Mar/2024 00:53:40] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [02/Mar/2024 00:53:47] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [02/Mar/2024 00:53:47] "OPTIONS /chatbot HTTP/1.1" 200 -
127.0.0.1 - - [02/Mar/2024 00:53:47] "POST /chatbot HTTP/1.1" 200 -
127.0.0.1 - - [02/Mar/2024 00:53:47] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [02/Mar/2024 00:53:48] "POST /chatbot HTTP/1.1" 200 -
_________________________________________________________________________________________
thanks for fast responses btw :) & sorry for bothering too much

**Comment by met4citizen** [comment]
If I understand the current situation correctly, the assistant's reply still doesn't come through from the Python code to the web app. A couple of things come to mind that you might consider.

First, before the app sends the request to the completions API, it sends the string to the GPT's moderation API. If this fails, or if the app receives a flagged response, the app never sends the request to the completions API.

Second, the response you send to the web app isn't right. Here is an example request and the streamed response from Safari browser's debugger:

Request to GPT:

```javascript
{"model":"gpt-3.5-turbo","messages":[{"role":"user","content":"Tell me a joke"}],"temperature":1,"presence_penalty":0,"frequency_penalty":0,"max_tokens":1000,"stream":true}
```

Streamed response from GPT:

```
data: {"id":"chatcmpl-8yDv6isoXkNtoFc45N1uPAUlhrQSK","object":"chat.completion.chunk","created":1709363880,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_2b778c6b35","choices":[{"index":0,"delta":{"role":"assistant","content":""},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8yDv6isoXkNtoFc45N1uPAUlhrQSK","object":"chat.completion.chunk","created":1709363880,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_2b778c6b35","choices":[{"index":0,"delta":{"content":"Why"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8yDv6isoXkNtoFc45N1uPAUlhrQSK","object":"chat.completion.chunk","created":1709363880,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_2b778c6b35","choices":[{"index":0,"delta":{"content":" was"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8yDv6isoXkNtoFc45N1uPAUlhrQSK","object":"chat.completion.chunk","created":1709363880,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_2b778c6b35","choices":[{"index":0,"delta":{"content":" the"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8yDv6isoXkNtoFc45N1uPAUlhrQSK","object":"chat.completion.chunk","created":1709363880,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_2b778c6b35","choices":[{"index":0,"delta":{"content":" math"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8yDv6isoXkNtoFc45N1uPAUlhrQSK","object":"chat.completion.chunk","created":1709363880,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_2b778c6b35","choices":[{"index":0,"delta":{"content":" book"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8yDv6isoXkNtoFc45N1uPAUlhrQSK","object":"chat.completion.chunk","created":1709363880,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_2b778c6b35","choices":[{"index":0,"delta":{"content":" sad"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8yDv6isoXkNtoFc45N1uPAUlhrQSK","object":"chat.completion.chunk","created":1709363880,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_2b778c6b35","choices":[{"index":0,"delta":{"content":"?\n\n"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8yDv6isoXkNtoFc45N1uPAUlhrQSK","object":"chat.completion.chunk","created":1709363880,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_2b778c6b35","choices":[{"index":0,"delta":{"content":"Because"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8yDv6isoXkNtoFc45N1uPAUlhrQSK","object":"chat.completion.chunk","created":1709363880,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_2b778c6b35","choices":[{"index":0,"delta":{"content":" it"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8yDv6isoXkNtoFc45N1uPAUlhrQSK","object":"chat.completion.chunk","created":1709363880,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_2b778c6b35","choices":[{"index":0,"delta":{"content":" had"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8yDv6isoXkNtoFc45N1uPAUlhrQSK","object":"chat.completion.chunk","created":1709363880,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_2b778c6b35","choices":[{"index":0,"delta":{"content":" too"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8yDv6isoXkNtoFc45N1uPAUlhrQSK","object":"chat.completion.chunk","created":1709363880,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_2b778c6b35","choices":[{"index":0,"delta":{"content":" many"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8yDv6isoXkNtoFc45N1uPAUlhrQSK","object":"chat.completion.chunk","created":1709363880,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_2b778c6b35","choices":[{"index":0,"delta":{"content":" problems"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8yDv6isoXkNtoFc45N1uPAUlhrQSK","object":"chat.completion.chunk","created":1709363880,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_2b778c6b35","choices":[{"index":0,"delta":{"content":"."},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8yDv6isoXkNtoFc45N1uPAUlhrQSK","object":"chat.completion.chunk","created":1709363880,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_2b778c6b35","choices":[{"index":0,"delta":{},"logprobs":null,"finish_reason":"stop"}]}

data: [DONE]


```

Note the "data: " prefix before each data chunk and two line breaks after each data chunk.

Now, I assume ChatterBot always returns its response in one string, so you can also send it in one chunk, but the "choices" message structure has to be the same, there has to be the "data: " prefix, and the stream must end in "data: [DONE]\n\n" line.
