### ISSUE TITLE
Google Translate tts

### ISSUE THREAD

**Issue by tomyslavs** [met4citizen/TalkingHead#70]
Is it possible to use Google Translate tts endpoint instead of 

ttsEndpoint: "https://eu-texttospeech.googleapis.com/v1beta1/text:synthesize",

**Comment by met4citizen** [comment]
No, only the official Google Cloud Text-to-Speech API endpoints and compatible API proxies are supported. That said, the endpoint is only used in the `speakText` method. If you use `speakAudio` method instead, you can generate your audio using any TTS engine you like in your app. A common caveat here is that not all TTS engines provide word-level timestamps, which are needed for accurate lip-sync. I haven't checked, but I'm pretty sure that Google Translate TTS can't provide them.

**Comment by DomoMKT** [comment]
you're in luck! you can find a high-quality, latency-friendly text-to-speech solution at [www.nemesyslabs.com](https://www.nemesyslabs.com).

**Comment by met4citizen** [comment]
@DomoMKT Unfortunately, the suggested text-to-speech API does not provide word-level timestamps, which are needed in the TalkingHead project for accurate lip-sync.

**Comment by DomoMKT** [comment]
I’m part of the support team, I can add it for you today

**Comment by GeronimoKTT** [comment]
@tomyslavs @met4citizen word-level timestamps api was added, check here [nemesys labs integration](https://www.nemesyslabs.com/#integration)

**Comment by met4citizen** [comment]
Thank you @DomoMKT and @GeronimoKTT ! - I tried the new timestamps API in my test environment, and it looks very promising so far. The audio quality is good, and the word-audio alignment information seems accurate.

However, I could only access the API through a proxy because it seems that CORS is not allowed on the endpoints. - Would it be possible to enable CORS for all origins so that the API can be called directly from browser JavaScript?

While visiting the website, I didn’t find any company information, Terms of Service, Privacy Policy, or details about usage limits. I understand that the service is new/free, but having this kind of information about the company and its business model would help put my mind at ease. From a more technical perspective, I would like to know, for example, the maximum size of the input text and whether there are any limits on the number or frequency of requests.

I will run further tests later this week. If everything goes well, I will publish a simple code example next week demonstrating how to use Nemesys Labs' text-to-speech with the TalkingHead class.

**Comment by GeronimoKTT** [comment]
@met4citizen thanks for these!, those updates are currently under review and will get deployed in a couple of hours with more improvements.

**Comment by GeronimoKTT** [comment]
> Thank you [@DomoMKT](https://github.com/DomoMKT) and [@GeronimoKTT](https://github.com/GeronimoKTT) ! - I tried the new timestamps API in my test environment, and it looks very promising so far. The audio quality is good, and the word-audio alignment information seems accurate.
> 
> However, I could only access the API through a proxy because it seems that CORS is not allowed on the endpoints. - Would it be possible to enable CORS for all origins so that the API can be called directly from browser JavaScript?
> 
> While visiting the website, I didn’t find any company information, Terms of Service, Privacy Policy, or details about usage limits. I understand that the service is new/free, but having this kind of information about the company and its business model would help put my mind at ease. From a more technical perspective, I would like to know, for example, the maximum size of the input text and whether there are any limits on the number or frequency of requests.
> 
> I will run further tests later this week. If everything goes well, I will publish a simple code example next week demonstrating how to use Nemesys Labs' text-to-speech with the TalkingHead class.

Those were updated!

**Comment by met4citizen** [comment]
Thank you.

I just tested that the CORS is now enabled and the API can be called directly from browser JavaScript. Great!

However, in this new version there seems to be something wrong with the timestamps. For example, as you can see below, word durations (end - start) are just a few milliseconds long, which is not realistic. In the previous version, the times were spot on, so hopefully, this is just a small bug and easy to fix.

```json
{
    "timestamps_map": [
        { "word": "I'm", "start": "0.187", "end": "0.190" },
        { "word": "using", "start": "0.312", "end": "0.317" },
        { "word": "a", "start": "0.687", "end": "0.688" },
        { "word": "text-to-speech", "start": "0.750", "end": "0.764" },
        { "word": "solution", "start": "1.725", "end": "1.733" },
        { "word": "from", "start": "2.262", "end": "2.266" },
        { "word": "Nemesys", "start": "2.462", "end": "2.469" },
        { "word": "Labs", "start": "3.062", "end": "3.066" }
    ],
    "audio_base64": "SUQzAwAAAAACBlRJVDIAA..."
}
```

**Comment by GeronimoKTT** [comment]
@met4citizen **Issue fixed**, thanks for flagging that! we've added our discord link in the website [nemesyslabs.com](https://www.nemesyslabs.com/), so you can reach us from there if possible for faster responses!

**Comment by met4citizen** [comment]
Thanks again, @[GeronimoKT](https://github.com/GeronimoKTT)T ! The timestamps look better now. If I have any further issues, I will report them to your new Discord service.

Note: I just published a simple code example on how to use the TalkingHead class with Nemesys Labs text-to-speech (English only). Here are the links: [[Source code]](https://github.com/met4citizen/TalkingHead/blob/main/examples/nemesyslabs.html) [[Test it]](https://met4citizen.github.io/TalkingHead/examples/nemesyslabs.html)
