### ISSUE TITLE
Issue with some voices with google text to speech 

### ISSUE THREAD

**Issue by audreytimbani** [met4citizen/TalkingHead#73]
Voice :  `en-GB-Studio-B`

Error :
```

{
  "error": {
    "code": 400,
    "message": "`\u003cmark\u003e` tags are not currently supported by Studio voices.",
    "status": "INVALID_ARGUMENT"
  }
}
```

**Comment by audreytimbani** [comment]
Got it

**Error Explanation:** The error message states that "<mark> tags are not currently supported by Studio voices," leading to an INVALID_ARGUMENT status. This suggests that while you are using valid SSML syntax, the specific voice you selected does not support this feature .

**Feature Limitation:** As of now, Studio voices, despite being generally available since February 26, 2024, do not implement support for <mark> tags. Users have reported similar issues and have suggested filing a feature request for this capability

**Comment by met4citizen** [comment]
Yes, this is a known issue. From the TalkingHead README: "The used [Google] voice must support SSML and \<mark> tags that are needed to get word-level timestamps. Currently, Google supports SSML and \<mark> tags when using Standard, Wavenet, Neural2, News, or Casual voice types."
