### ISSUE TITLE
Bug: Importing new avatars broken

### ISSUE THREAD

**Issue by Dunya-8a** [met4citizen/TalkingHead#75]
The app breaks with avatars other than the default Brunette (in index.html). This is the main error I'm getting:

```
TypeError: Cannot read properties of undefined (reading 'needsUpdate')
    at TalkingHead.animate (talkinghead.mjs:2399:15)
```

which leads me to here:

```
if ( !j.needsUpdate ) {
        Object.assign(j,{ base: (this.mood.baseline[i] || 0) + ( 1 + vol/255 ) * Math.random() / 5, needsUpdate: true });
      }
```

However, even when commenting this out, there are other functions that refer to ```needsUpdate``` and break.

I traced it back and the issue seems to have been introduced with ```commit fbad291d14c8c45632d4ed084cbeb01b4801a46c "Improved morph target animation system"```.

I am not sure what's different between the Brunette avatar and the ones I am importing (as glb files). They were all generated with Ready Player Me and working before.

Additionally, I went back to before the commit that introduced the new functions. Even though the import worked here, I couldn't use most emotions (other than neutral and happy) or most emoji on the imported avatars. This may be a separate issue, but I thought I first mention it here. The emoji work on new avatars in the minimal example, however!

**Comment by met4citizen** [comment]
The most likely reason for the error is that your avatar doesn't have all the necessary morph targets (blend shapes). — Did you follow the instructions in the README Appendix A when you downloaded your model?

If you did, can you provide the Ready Player Me URL to that GLB file so that I can download it and reproduce the problem in my test environment. Thanks.

**Comment by Dunya-8a** [comment]
My bad, it works with the added morph targets! Apologies, I think when I tried it in October it worked even without the morph targets (or I forgot that I had followed the instructions) and I forgot. Thank you so much for the swift response.
